const MODULE_PREFIX = `@@BBATCH_REDUX_UPDATE`;
export const START_BATCH_UPDATES = `${MODULE_PREFIX}/START_BATCH_UPDATES`;
export const FLUSH_BATCH_UPDATES = `${MODULE_PREFIX}/FLUSH_BATCH_UPDATES`;

export const ADD_BATCHED_ACTION = `${MODULE_PREFIX}/ADD_BATCHED_ACTION`;
export const CLEAR_BATCHED_ACTIONS = `${MODULE_PREFIX}/CLEAR_BATCHED_ACTIONS`;
export const SET_INBATCHMODE = `${MODULE_PREFIX}/SET_INBATCHMODE`;